spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;MODE=MySQL;
    username: SA
    password:
    hikari:
      maximum-pool-size: 4
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 10000
          time_zone: Asia/Seoul